version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sion
      - MYSQL_DATABASE=findRoom
    networks:
      - sionwork

  spring:
    image: springboot-sion
    container_name: spring
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/findRoom
      SPRING_DATASOURCE_USERNAME: sion
      SPRING_DATASOURCE_PASSWORD: tldhschlrh1523
    networks:
      - sionwork

networks:
  sionwork:
    driver: bridge