server:
  port: 8181

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/findRoom
    username: findRoom
    password: tldhschlrh1523
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false

  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
