# 워크 플로우 이름
name: Java CI with Gradle


# 워크 플로우가 언제 실행 될지를 정한다.
on:
  push:
    branches: [ "dev" ]


jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      # SOURCE 단계 - 저장소 Checkout
      - name: Checkout-source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Gradle 실행권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew



      # Spring boot application 빌드
      - name: Build with gradle
        run: ./gradlew clean build

      # docker image 빌드
      - name: Build docker image
        run: docker build -t  rlatldhs12513/findroom .

      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker hub 퍼블리시
      - name: Publish to docker hub
        run: docker push  rlatldhs12513/findroom

      # WAS 인스턴스 접속 & 애플리케이션 실행
      - name: Connect to WAS & Execute Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            MARIADB_CONTAINER=$(docker ps -aqf "name=mariadb")
              
            docker stop $(docker ps -aqf "name=findroomcon")
            docker rm $(docker ps -aqf "name=findroomcon")
              
            docker pull rlatldhs12513/findroom
              
            if [ -z "$MARIADB_CONTAINER" ] || [ -z "$(docker ps -qf "name=mariadb")" ]; then
              echo "MariaDB container not found or not running. Starting a new one..."
              docker run -d --name mariadb --network sionwork \
                -e MYSQL_ROOT_PASSWORD=root \
                -e MYSQL_DATABASE=newSion \
                -v mariadb_data:/var/lib/mysql \
                -p 3306:3306 \
                mariadb:latest
            fi
            
            docker run -d --name findroomcon --network sionwork \
              -e SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/newSion \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=root \
              -p 8181:8181 \
              rlatldhs12513/findroom
